language: node_js

node_js:
  - 7

services:
    - docker

before_install:
    - docker build --target development -t elements-rest:development ./rest
    - docker run -dp 8080:8080 elements-rest
    - docker ps -a

script:
  - docker run elements-rest /bin/sh -c "cd rest; npm test"
