version: "3"

services:
  rest:
    build: ./rest
    image: rest:api
    command: nodemon -L --inspect=0.0.0.0:5858 ./app.js
    volumes:
      - ./rest:/elements/rest
    ports:
      - "8080:8080"
      - "5858:5858"
